azure-pipelines.yml, config/nonprod.tfvars, config/prod.tfvars, terraform/00-init.tf, terraform/01-inputs-required.tf, terraform/02-interpolated-defaults.tf, terraform/10-sendgrid.tf
https://tools.hmcts.net/jira/browse/DTSPO-1597
Pipeline for creating subusers in the new centralised SendGrid accounts
```
[ ] Yes
[x ] No
```
=> DTSPO-1597 - Sendgrid subusers

terraform/10-sendgrid.tf
https://tools.hmcts.net/jira/browse/DTSPO-1597
Updated key vault secret name to use full username
```
[ ] Yes
[x] No
```
=> DTSPO-1597 - Sendgrid subusers 2

README.md, terraform/10-sendgrid.tf
https://tools.hmcts.net/jira/browse/DTSPO-1597
Name prefix update to subuser password key vault secret
Initial readme update. API key retrieval section to be updated using PR example from DTSPO-1452  once completed.
```
[ ] Yes
[x ] No
```
=> DTSPO-1597 - Sendgrid subusers - 3

terraform/10-sendgrid.tf
Removed sender eligible api permission
```
[ ] Yes
[ X] No
```
=> DTSPO-1452 - updated api key scope

config/nonprod.tfvars
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> Show tell demo - subuser

config/nonprod.tfvars
Removing demo user created for show and tell.
```
[ ] Yes
[ x] No
```
=> Show/Tell - removing demo user

config/nonprod.tfvars
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> Added cmc to the config to increase sendgrid limit

config/nonprod.tfvars, config/prod.tfvars
This PR is to add new account for civil damages.
```
=> Add civil damages account

config/nonprod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-2296
Added payments to nonprod.tfvars file
```
[ ] Yes
[x] No
```
=> DTSPO-2296 - Payment Sendgrid

config/nonprod.tfvars
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPO-2296
Change description
Recreating nonprod account called payment instead of payments
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> DTSPO-2296 - Payment Sendgrid NonProd

config/prod.tfvars
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPO-2296
Change description
Recreating prod sendgrid account called payment
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> DTSPO-2296 Payment Sendgrid Prod

config/nonprod.tfvars, config/prod.tfvars
Add civil account 
```
[ ] Yes
[x] No
```
=> add civil serivce account

config/nonprod.tfvars, config/prod.tfvars
https://tools.hmcts.net/jira/browse/RDCC-3030
Add sendgrid config for reference data
```
[ ] Yes
[X] No
```
=> Add sendgrid config for reference data

config/nonprod.tfvars, config/prod.tfvars
https://tools.hmcts.net/jira/browse/AM-1521
Add send grid config for access management
```
[ ] Yes
[X] No
```
=> Add sendgrid config for access management

config/nonprod.tfvars, config/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6247 
Private law sendgrid account creation for prod and non prod
```
[ ] Yes
[x] No
```
=> private-law sendgrid account creation

CODEOWNERS
https://tools.hmcts.net/jira/browse/DTSPO-8338
```
[ ] Yes
[x] No
```
=> DTSPO-8338 Add Codeowners

azure-pipelines.yml, terraform/00-init.tf
=> DTSPO-8338 upgrade terraform version

terraform/adoption.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> account create for adoption

terraform/dcs.tf
https://tools.hmcts.net/jira/browse/DTSPO-13651
Moving DCS from using Mailrelay2 service to using SendGrid
```
[ ] Yes
[x] No
```
=> onboarding dcs

terraform/panorama.tf
https://tools.hmcts.net/jira/browse/DTSPO-13653
Migrate Panorama to Sendgrid
```
[ ] Yes
[ ] No
```
=> adding the panorama to sendgrid

terraform/inputs.tf, terraform/modules/sendgrid/inputs-required.tf, terraform/modules/sendgrid/sendgrid.tf, terraform/uipath.tf
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[x] No
```
=> DTSPO-13652-refactor

components/sendgrid/utiac.tf
N/A
- [] README and other documentation has been updated / added (if needed)
- [] tests have been updated / new tests has been added (if needed)
- [] Does this PR introduce a breaking change
=> Add SendGrid and Azure DNS modules for UTIAC

components/sendgrid/utiac.tf
=> Update SendGrid domains in utiac.tf

README.md
removing outdated config instructions### Checklist
=> remove outdated config instructions

components/sendgrid/darts-dets.tf
N/A
Import borked sendgrid user.
=> fix: import borked user

components/modules/azure_dns/dns_name.tf, components/sendgrid/pre.tf
=> feat: added PRE Sendgrid account for B2C

components/sendgrid/bau.tf
https://tools.hmcts.net/jira/browse/DTSPO-25354
Adding BAU specific sendgrid account for all BAU requirements that might arise
=> Adding BAU specific sendgrid account for all BAU requirements that might arise
